### ISSUE TITLE
Cannot find src with path.. error when trying to upload worker

### ISSUE THREAD

**Issue by KobaKhit** [iron-io/issues#101]
I downloaded a worker that my coworker created on his laptop. So the first thing, I have a different environment(we both are using macs os x, though). I ran it successfully in terminal and now I am trying to upload it to ironWorker with the changes I made. I tried to make my environment look like my coworker's. However, I get an error. Below is the output. The problem is the "cannot find src with..." The HTML.py is in the that directory, but something is wrong. Help appreciated.

```
Dostres-MacBook-Pro:SFDC Updater Koba$ iron_worker upload Worker------> Creating client
        Project 'SFDC UTM Updater' with id='5383f61c63a6ad0005000013'
------> Creating code package
        Found workerfile with path='Worker.worker'
        Detected exec with path='SFDC_UTM_Updater.py' and args='{}'
        Merging file with path='iron.json' and dest=''
        Merging file with path='SFDC_UTM_Updater.py' and dest=''
        Merging file with path='/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/HTML.py' and dest=''
        Merging dir with path='/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Shippy' and dest=''
        Adding python pip dependency with name='requests' and version=''
        Adding python pip dependency with name='beatbox' and version=''
        Adding python pip dependency with name='python-dateutil' and version=''
        Adding python pip dependency with name='mandrill' and version=''
        Adding python pip dependency with name='isoweek' and version=''
        Adding python pip dependency with name='pandas' and version=''
        Adding python pip dependency with name='numpy' and version=''
        Adding python pip dependency with name='gspread' and version=''
        Code package name is 'Worker'
------> Uploading code package 'Worker'
        Fixating pip dependencies
        Can't find src with path='/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/HTML.py'
/Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_core-1.0.4/lib/iron_core/iron_logger.rb:50:in `raise_exception': Can't find src with path='/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/HTML.py' (IronCore::Error)
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_core-1.0.4/lib/iron_core/iron_logger.rb:27:in `error'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/feature/base.rb:19:in `block in container_add'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/fetcher.rb:101:in `call'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/fetcher.rb:101:in `fetch_to_file'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/feature/base.rb:17:in `container_add'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/feature/common/merge_file.rb:20:in `bundle'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/code/base.rb:229:in `block in bundle'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/code/base.rb:228:in `each'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/code/base.rb:228:in `bundle'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/code/base.rb:295:in `create_container'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/client.rb:105:in `codes_create'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/client.rb:18:in `method_missing'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/lib/iron_worker_ng/cli.rb:108:in `upload'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/gems/iron_worker_ng-1.5.0/bin/iron_worker:116:in `<top (required)>'
    from /Users/Koba/.rvm/rubies/ruby-2.1.2/bin/iron_worker:23:in `load'
    from /Users/Koba/.rvm/rubies/ruby-2.1.2/bin/iron_worker:23:in `<main>'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/bin/ruby_executable_hooks:15:in `eval'
    from /Users/Koba/.rvm/gems/ruby-2.1.2@global/bin/ruby_executable_hooks:15:in `<main>'
Dostres-MacBook-Pro:SFDC Updater Koba$ 
```

**Comment by KobaKhit** [comment]
Resolved. Just had to figure out the right environment structure.
