### ISSUE TITLE
Ssl error connecting to Rackspace

### ISSUE THREAD

**Issue by pax95** [iron-io/issues#15]
Hi 

When connecting IronMQ to Rackspace i get an java error

javax.net.ssl.SSLException: Received fatal alert: unexpected_message
    at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:190)[:1.6]
    at com.sun.net.ssl.internal.ssl.Alerts.getSSLException(Alerts.java:136)[:1.6]
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1839)[:1.6]
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1019)[:1.6]
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1203)[:1.6]
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1230)[:1.6]
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1214)[:1.6]
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:434)[:1.6]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:166)[:1.6]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:133)[:1.6]
    at io.iron.ironmq.Client.singleRequest(Client.java:115)[file:/Users/prebenasmussen/git/iron_mq_java/target/classes/:]
    at io.iron.ironmq.Client.request(Client.java:84)[file:/Users/prebenasmussen/git/iron_mq_java/target/classes/:]
    at io.iron.ironmq.Client.post(Client.java:73)[file:/Users/prebenasmussen/git/iron_mq_java/target/classes/:]
    at io.iron.ironmq.Queue.push(Queue.java:161)[file:/Users/prebenasmussen/git/iron_mq_java/target/classes/:]

**Comment by carimura** [comment]
@treeder @edsrzf FYI help if possible

**Comment by odeits** [comment]
Had similar problem with python client. Problem was with the ssl version. The solution in the python client might be helpful. 

https://github.com/iron-io/iron_mq_python/commit/eb03466632e573ed27d5ab5d0c6e4cb0adbcad93

@paddyforan might have more insight.

**Comment by pax95** [comment]
@carimura @odeits I fixed the problem in the ironmq java lib and submitted a pull request. Take a look and see if it's ok

**Comment by treeder** [comment]
cc @edsrzf

**Comment by carimura** [comment]
Old issue.. can we close this?

**Comment by pax95** [comment]
yeah - I have tested it against Rackspace.
