### ISSUE TITLE
Unable to install some python module upgrades (pymongo for example) when module already installed

### ISSUE THREAD

**Issue by ScottEAdams** [iron-io/issues#35]
As pymongo is already installed it makes it impossible to install/upgrade the latest version using the same trick as posted http://stackoverflow.com/questions/13285901/how-to-bundle-python-dependancies-in-ironworker/13296163#13296163

To start with it would be good to update pymongo in general to 2.3 whilst figuring out a long term solution.

Downloading/unpacking pymongo==2.3
  Running setup.py egg_info for package pymongo

Installing collected packages: pymongo
  Found existing installation: pymongo 2.2.1
    Uninstalling pymongo:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 228, in run
    requirement_set.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1089, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 476, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1391, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 248, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 297, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 248, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/bson/tz_util.pyc'

Storing complete log in /task/.pip/pip.log

**Comment by frommww** [comment]
@iced  or @paddyforan can one of you update this issue so that scott has some visibility on it?

**Comment by dbgrandi** [comment]
+1, this would be super helpful for my current situation.

**Comment by treeder** [comment]
We'll be coming out with a new VM for our workers soon that should resolve this issue. Python makes it hard to override the installed libraries for some reason. We'll update this when it's ready.

**Comment by dbgrandi** [comment]
Thanks, @treeder, I'll keep an eye out for updates.

**Comment by iced** [comment]
iron_worker_ng 0.16.0 should solve this issue. requirements.txt will be available in 0.16.1 (tomorrow maybe).

**Comment by iced** [comment]
actually grab 0.16.2 (thanks to pip maintainers & apple), requirements postponed to 0.16.3.
