### ISSUE TITLE
iron_worker .worker file parsing error messages are way too cryptic

### ISSUE THREAD

**Issue by rbpasker** [iron-io/issues#41]
for example, this is from leaving out an argument for dir:

/Users/rbp/.rvm/gems/ruby-1.9.3-p362/gems/iron_worker_ng-0.15.0/lib/iron_worker_ng/code/base.rb:85:in `eval': wrong number of arguments (0 for 1) (ArgumentError)
    from (eval):7:in`block (2 levels) in initialize'

this is from not having a correct argument for dir:

```
    Found workerfile with path='contextio.worker'
```

/Users/rbp/.rvm/gems/ruby-1.9.3-p362/gems/iron_worker_ng-0.15.0/lib/iron_worker_ng/code/base.rb:85:in `eval': (eval):7: syntax error, unexpected $end (SyntaxError)
    from /Users/rbp/.rvm/gems/ruby-1.9.3-p362/gems/iron_worker_ng-0.15.0/lib/iron_worker_ng/code/base.rb:85:in`block (2 levels) in initialize'
    from /Users/rbp/.rvm/gems/ruby-1.9.3-p362/gems/iron_worker_ng-0.15.0/lib/iron_worker_ng/fetcher.rb:53:in `call'

**Comment by iced** [comment]
Will fix in next gem release.
