### ISSUE TITLE
iron_worker - Parse.com's javascript sdk works locally but not on server

### ISSUE THREAD

**Issue by ssr1ram** [iron-io/issues#56]
For some reason, when using the Parse.com javascript sdk in an iron_worker nodejs worker it works when run locally, but bombs when I attempt to run it after uploading to the server.

What this then forced me to do is to resort to Parse.com's REST api.

Here is the log

task/node_modules/parse/parse.min.js:1
ach(r.keys(e),fu
      ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Object.t._each (/task/node_modules/parse/parse.min.js:1:17584)
    at Object.t._decode (/task/node_modules/parse/parse.min.js:1:17482)
    at n.extend._finishFetch._opSetQueue (/task/node_modules/parse/parse.min.js:1:37588)
    at t._each (/task/node_modules/parse/parse.min.js:1:17604)
    at Array.forEach (native)
    at Function.S.each.S.forEach (/task/node_modules/parse/parse.min.js:1:1702)
    at Object.t._each (/task/node_modules/parse/parse.min.js:1:17577)
    at n.extend._finishFetch (/task/node_modules/parse/parse.min.js:1:37547)
    at t.Query.first.o.success.t (/task/node_modules/parse/parse.min.js:1:60133)

**Comment by paddycarver** [comment]
@ssr1ram Would you mind posting the version of node.js you're running locally? My first instinct is to guess that there's a mismatch between the version you're running locally and the version on our server.

After that, I'll take a look through the module and see if I can figure out what's going wrong. A minimal code sample that demonstrates the issue would be awesome for debugging this.

**Comment by ssr1ram** [comment]
Hi,

The local node version is v0.8.14 It could be a bit tricky getting a code
sample out since we went REST, but I'll look into it.

Sriram

**Comment by ssr1ram** [comment]
Just tried it and the Parse javascript calls seem to be working, no need to resort to REST.
I see that you are using node v0.8.8. It would help to know when you guys change the version etc. 
In fact, it would be great if we could specify the node version in the .worker file 
(if you guys were using something like https://github.com/creationix/nvm , the .worker file could simply do a 'nvm use vx.y.z' )
