### ISSUE TITLE
404 error: Log not found 

### ISSUE THREAD

**Issue by calebjclark** [iron-io/issues#68]
About 30 minutes ago we started getting 404 errors when uploading a new code package with iron_worker_ng. Error and stacktrace:

HTTP 404 Error. {"msg":"Log not found."}
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/wrappers/typhoeus_wrapper.rb:66:in `handle_response'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/wrappers/typhoeus_wrapper.rb:52:in`get'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/client.rb:89:in `block in get'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/client.rb:113:in`perform_op'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/client.rb:88:in `get'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_core-0.6.0/lib/iron_core/client.rb:182:in`get'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.3/lib/iron_worker_ng/api_client.rb:86:in `tasks_log'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.3/lib/iron_worker_ng/client.rb:229:in`tasks_log'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.3/lib/iron_worker_ng/client.rb:16:in `method_missing'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.3/lib/iron_worker_ng/client.rb:110:in`codes_create'
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.3/lib/iron_worker_ng/client.rb:16:in `method_missing'

**Comment by treeder** [comment]
Hi @calebclark , what log are you trying to get while uploading?  There are only logs for tasks/jobs. 

Or if you are trying to get it on tasks, sometimes the log's take a second or two to be available after it's finished. Are you trying to get the log immediately after a job completes (or while it's running)?

**Comment by calebjclark** [comment]
I'm not trying to request any logs. I'm just using IronWorkerNG::Client to create a new code package (codes.create).

-Caleb

**Comment by calebjclark** [comment]
@treeder, our exact same uploading code was working yesterday. It stopped working at some point today.

**Comment by calebjclark** [comment]
It looks like the build is erroring out. When I log into HUD I see that there are build errors, however, the log is empty. I think that may be what is causing the issue in the iron_worker_ng gem.

**Comment by calebjclark** [comment]
@treeder, I'm getting the the same "Log not found" error when I use iron_worker from the command line:

```
% iron_worker upload check-profile
------> Creating client
        Project 'Prd - Addons by MLabs' with id='513de83b2267d8470e002a7c'
------> Creating code package
        Found workerfile with path='check-profile.worker'
        Detected exec with path='check-profile.rb' and args='{}'
        Adding ruby gem dependency with name='fanforce-api' and version='~> 0.9'
        Adding ruby gem dependency with name='fanforce-workers' and version='~> 0.7'
        Adding ruby gem dependency with name='fullcontact' and version='~> 0.4'
        Adding ruby gem dependency with name='iron_cache' and version='~> 1.4'
        Merging file with path='.pluginenv.rb' and dest=''
        Merging file with path='../lib/fullcontact_sync.rb' and dest=''
        Code package name is 'check-profile'
------> Uploading and building code package 'check-profile'
        Remote building worker
/Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/wrappers/typhoeus_wrapper.rb:66:in `handle_response': HTTP 404 Error. {"msg":"Log not found."} (Rest::HttpError)
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/wrappers/typhoeus_wrapper.rb:52:in `get'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/client.rb:89:in `block in get'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/client.rb:113:in `perform_op'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/rest-2.6.0/lib/rest/client.rb:88:in `get'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_core-0.6.0/lib/iron_core/client.rb:182:in `get'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.2/lib/iron_worker_ng/api_client.rb:86:in `tasks_log'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.2/lib/iron_worker_ng/client.rb:229:in `tasks_log'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.2/lib/iron_worker_ng/client.rb:16:in `method_missing'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.2/lib/iron_worker_ng/client.rb:110:in `codes_create'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.2/lib/iron_worker_ng/client.rb:16:in `method_missing'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.2/lib/iron_worker_ng/cli.rb:82:in `upload'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/gemsets/addons-by-mlabs/gems/iron_worker_ng-0.16.2/bin/iron_worker:104:in `<top (required)>'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/bin/iron_worker:23:in `load'
    from /Users/calebclark/.rbenv/versions/1.9.3-p194/bin/iron_worker:23:in `<main>'
```

**Comment by calebjclark** [comment]
@treeder It's only throwing the error when "full_remote_build true" is included in the worker file.

**Comment by calebjclark** [comment]
Any chance this can be fixed before the weekend? It's put a freeze on most of our work since the majority of our workers use full_remote_build.

**Comment by treeder** [comment]
Looking into it.

**Comment by calebjclark** [comment]
@treeder, I discovered the problem. Our account was maxed out, and instead of telling us we need to upgrade our account (which we would have happily done), iron_worker is throwing the "Log not found".

Once we upgraded, the cryptic error message went away.

**Comment by treeder** [comment]
Ahh, thanks for figuring it out. I reopened this so we can show a more appropriate error for this case.
