### ISSUE TITLE
SSL Error with NodeJs remote build and npm install

### ISSUE THREAD

**Issue by artraxus** [iron-io/issues#93]
Hello and thanks for iron.io.

When I use the build command "npm install" in my .worker file to package dependencies remotely through uploaded package.json.
I get this error:

<pre>
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/ftp
npm ERR! Error: SSL Error: CERT_UNTRUSTED
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/npm/node_modules/request/main.js:525:26)
npm ERR!     at ClientRequest.g (events.js:185:14)
npm ERR!     at ClientRequest.EventEmitter.emit (events.js:88:17)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1455:7)
npm ERR!     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:111:23)
npm ERR!     at CleartextStream.socketOnData [as ondata] (http.js:1366:20)
npm ERR!     at CleartextStream.CryptoStream._push (tls.js:495:27)
npm ERR!     at SecurePair.cycle (tls.js:849:20)
npm ERR!     at EncryptedStream.CryptoStream.write (tls.js:230:13)
npm ERR!     at Socket.ondata (stream.js:38:26)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.2.0-38-virtual
npm ERR! command "nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /task/__build__
npm ERR! node -v v0.8.8
npm ERR! npm -v 1.1.59
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /task/__build__/npm-debug.log
npm ERR! not ok code 0
</pre>

**Comment by jamespeerless** [comment]
I'm having the exact same issue.  Completely blocking my team.

**Comment by Stephenitis** [comment]
There is a temporary fix for this 

add the following to your .worker file.
build "npm config set strict-ssl false; npm install --production"

alternatively you can add the modules directory and the package.json and upload the modules locally instead of building remotely
